version: "3"
services:
  app:
    image: webapp
    ports:
      - "81:80"
    restart: always

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - URI=http://gosling-pro.duckdns.org:3001/api
    container_name: web-application
