version: "3"
services:
  app:
    image: webapp
    ports:
      - "80:80"
    restart: always

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - URI=164.92.114.213:3001/api
    container_name: web-application
