version: "3"
services:
  app:
    image: webapp
    ports:
      - "81:80"
    restart: always
    environment:
      - REACT_APP_API_URL=http://gosling-pro.duckdns.org:3001/api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-application
