version: "3"
services:
  app:
    image: webapp
    ports:
      - "80:80"
    restart: always

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - URI=http://164.92.114.213:3000/api
    volumes:
      - /home/docker/volumes/nginx-front/nginx.conf:/etc/nginx/nginx.conf
    container_name: web-application
